### PR TITLE
adding --permanent-peer

### PR DESCRIPTION
**Pull request by jeremymv2**
This ensures that each service member keeps a member census state and that any member will not be excluded from the ring when attempting to re-join after having been shutdown.

Signed-off-by: Jeremy J. Miller <jm@chef.io>

### CODE REVIEW

**Comment by irvingpop** [comment]
hey just wanted to check before approving:   this change provides an improvement while leaving the `rm -rf ${DATA_MOUNT:-/mnt/hab}/*_sup` in place?   

I ask because my mental model is struggling with this:   I thought the idea of a permanent peer was one that persisted state data, even across restarts.

**Comment by jeremymv2** [comment]
The removal of the sup data only occurs if _all_ the services are shut down intentionally and manually (Zapp only shuts down individual containers independent of each other) - it won't happen on individual container restarts.

The removal is an extra layer of assurance that no corrupt state remains on the next start after a complete shutdown. Following a complete shutdown, on the next start, there is then no previous state, in which case everything should just re-establish fine.

The `--permanent-peer` helps when individual services bounce. In that case, the  `/hab/sup` is _not_ removed for that service. With this permanent peer option, the other members should remember the re-joining member when it returns and let it back in.

There are two scenarios being accounted for:
1. Individual container restarts (In which case, no data is removed and `--permanent-peer` should allow members to rejoin)
2. Troubleshooting requires manual intervention and a complete shutdown, in which case why not gratuitously remove all the sup data since you are intentionally trying to "reset" the entire environment, but preserving DB and ES data of course.

Hopefully with number 1 above, number 2 seldom ever is necessary.

**Comment by echohack** [comment]
@jeremymv2 I think this is an OK solution. It would be better to set up a bastion ring and connect to the bastion ring, but I don't think the customer plans to run this solution that way, so this is fine.

👍 

@irvingpop Permanent peer prevents a split brain scenario in a network of supervisors. This comment (and code) can be very helpful to read: https://github.com/habitat-sh/habitat/blob/00dd5c1c9e765bb25054a92e7d127e8b6554234d/components/butterfly/src/lib.rs#L18

**Review by echohack — COMMENTED** [review]
luda-giphy

**Comment by irvingpop** [comment]
👍 nice work gentlemen

**Pull request merged**
